name: scp-to-server
on:
  push:
    branches:
      - main

jobs:
  deploy-to-ssh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # - name: zip and backup current deployment on remote server
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     script: |
    #       zip -r backup/backup.zip public_html/


    - name: Copy _site directory to remote server
      if: ${{ success() }}
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "_site"
        target: "~/REPOSITORY"
        overwrite: true

    - name: move contents of _site directory up one level
      if: ${{ success() }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          mv REPOSITORY/_site/* REPOSITORY/ && rm -r REPOSITORY/_site
